baseURL = "//www.cesarolea.com/"
languageCode = "en-us"
title = "César Olea"
theme = "hugo-ink"
paginate = 5

copyright = "© Copyright César Olea 2020"

pygmentsstyle = "emacs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"

[params]
	subtitle = "Software Developer | CTO of [LoanPro](https://loanpro.io)"

	# Optional 64x64 avatar image.
#	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Rockofonia"
url = "/rockofonia"
weight = 4

[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/cesarolea"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/cesarolea"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[deployment]
[[deployment.targets]]
name = "prod"
URL = "s3://www.cesarolea.com?region=us-east-1"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true