#+HUGO_TYPE: podcast

* Rockofonia
Rockofonia was a podcast centered around Hard Rock and Heavy Metal. It
spanned two seasons with more than 200 episodes, and for a little
while it even was syndicated in the BC México area. Episodes either
feature [[https://usuario.cicese.mx/~jagm/index.html][Tony GM]] or myself as DJ.

** Now in Spanish
Rockofonia era un podcast de /Hard Rock/ y /Heavy Metal/. Logró más de
200 episodios, y por un tiempo incluso fue sindicado en el area de BC
México.

* List of Episodes
Episodes should be in chronological order for the most part.

** Pilot
{{< audio src="/media/rockofonia-piloto.mp3" >}}
Download: [[/media/rockofonia-piloto.mp3][rockofonia-piloto.mp3]]

** Episode 0
{{< audio src="/media/itbounce.mp3" >}}
Download: [[/media/itbounce.mp3][itbounce.mp3]]

** Episode 1
{{< audio src="/media/itbounce-1.mp3" >}}
Download: [[/media/itbounce-1.mp3][itbounce-1.mp3]]

** Episode 3
{{< audio src="/media/itbounce-3.mp3" >}}
Download: [[/media/itbounce-3.mp3][itbounce-3.mp3]]

** Episode 4
{{< audio src="/media/itbounce-4.mp3" >}}
Download: [[/media/itbounce-4.mp3][itbounce-4.mp3]]

** Episode 5
{{< audio src="/media/itbounce-5.mp3" >}}
Download: [[/media/itbounce-5.mp3][itbounce-5.mp3]]

** Episode 8
{{< audio src="/media/itbounce-8.mp3" >}}
Download: [[/media/itbounce-8.mp3][itbounce-8.mp3]]

** Episode 11
{{< audio src="/media/itbounce-11.mp3" >}}
Download: [[/media/itbounce-11.mp3][itbounce-11.mp3]]

** Episode 13
{{< audio src="/media/itbounce-13.mp3" >}}
Download: [[/media/itbounce-13.mp3][itbounce-13.mp3]]

** Episode 20
{{< audio src="/media/itbounce-20.mp3" >}}
Download: [[/media/itbounce-20.mp3][itbounce-20.mp3]]

** Episode 27
{{< audio src="/media/itbounce-27.mp3" >}}
Download: [[/media/itbounce-27.mp3][itbounce-27.mp3]]

** Episode 33
{{< audio src="/media/itbounce-33.mp3" >}}
Download: [[/media/itbounce-33.mp3][itbounce-33.mp3]]

** Episode 38
{{< audio src="/media/itbounce-38.mp3" >}}
Download: [[/media/itbounce-38.mp3][itbounce-38.mp3]]

** Episode 44
{{< audio src="/media/itbounce-44.mp3" >}}
Download: [[/media/itbounce-44.mp3][itbounce-44.mp3]]

** Episode 49
{{< audio src="/media/itbounce-49.mp3" >}}
Download: [[/media/itbounce-49.mp3][itbounce-49.mp3]]

** Episode 60
{{< audio src="/media/itbounce-60.mp3" >}}
Download: [[/media/itbounce-60.mp3][itbounce-60.mp3]]

** Episode 68
{{< audio src="/media/itbounce-68.mp3" >}}
Download: [[/media/itbounce-68.mp3][itbounce-68.mp3]]

** Episode 80
{{< audio src="/media/itbounce-80.mp3" >}}
Download: [[/media/itbounce-80.mp3][itbounce-80.mp3]]

** Episode 102
{{< audio src="/media/itbounce-102.mp3" >}}
Download: [[/media/itbounce-102.mp3][itbounce-102.mp3]]

** Episode 106
{{< audio src="/media/itbounce-106.mp3" >}}
Download: [[/media/itbounce-106.mp3][itbounce-106.mp3]]

** Episode 116
{{< audio src="/media/itbounce-116.mp3" >}}
Download: [[/media/itbounce-116.mp3][itbounce-116.mp3]]

** Episode 122
{{< audio src="/media/itbounce-122.mp3" >}}
Download: [[/media/itbounce-122.mp3][itbounce-122.mp3]]

** Episode 126
{{< audio src="/media/itbounce-126.mp3" >}}
Download: [[/media/itbounce-126.mp3][itbounce-126.mp3]]

** Episode 141
{{< audio src="/media/itbounce-141.mp3" >}}
Download: [[/media/itbounce-141.mp3][itbounce-141.mp3]]

** Episode 144
{{< audio src="/media/itbounce-144.mp3" >}}
Download: [[/media/itbounce-144.mp3][itbounce-144.mp3]]

** Episode 155
{{< audio src="/media/itbounce-155.mp3" >}}
Download: [[/media/itbounce-155.mp3][itbounce-155.mp3]]

** Episode 159
{{< audio src="/media/itbounce-159.mp3" >}}
Download: [[/media/itbounce-159.mp3][itbounce-159.mp3]]

** Episode 171
{{< audio src="/media/itbounce-171.mp3" >}}
Download: [[/media/itbounce-171.mp3][itbounce-171.mp3]]

** Episode 179
{{< audio src="/media/itbounce-179.mp3" >}}
Download: [[/media/itbounce-179.mp3][itbounce-179.mp3]]

** Episode 194
{{< audio src="/media/itbounce-194.mp3" >}}
Download: [[/media/itbounce-194.mp3][itbounce-194.mp3]]

** Episode 219
{{< audio src="/media/itbounce-219.mp3" >}}
Download: [[/media/itbounce-219.mp3][itbounce-219.mp3]]

** Episode 226
{{< audio src="/media/itbounce-226.mp3" >}}
Download: [[/media/itbounce-226.mp3][itbounce-226.mp3]]

** Episode 244
{{< audio src="/media/itbounce-244.mp3" >}}
Download: [[/media/itbounce-244.mp3][itbounce-244.mp3]]

** Episode 272
{{< audio src="/media/itbounce-272.mp3" >}}
Download: [[/media/itbounce-272.mp3][itbounce-272.mp3]]

** Episode 274
{{< audio src="/media/itbounce-274.mp3" >}}
Download: [[/media/itbounce-274.mp3][itbounce-274.mp3]]

** Episode 287
{{< audio src="/media/itbounce-287.mp3" >}}
Download: [[/media/itbounce-287.mp3][itbounce-287.mp3]]

** Episode 305
{{< audio src="/media/itbounce-305.mp3" >}}
Download: [[/media/itbounce-305.mp3][itbounce-305.mp3]]

** Episode 321
{{< audio src="/media/itbounce-321.mp3" >}}
Download: [[/media/itbounce-321.mp3][itbounce-321.mp3]]

** Episode 341
{{< audio src="/media/itbounce-341.mp3" >}}
Download: [[/media/itbounce-341.mp3][itbounce-341.mp3]]

** Episode 350
{{< audio src="/media/itbounce-350.mp3" >}}
Download: [[/media/itbounce-350.mp3][itbounce-350.mp3]]

** Episode 370
{{< audio src="/media/itbounce-370.mp3" >}}
Download: [[/media/itbounce-370.mp3][itbounce-370.mp3]]

** Episode 394
{{< audio src="/media/itbounce-394.mp3" >}}
Download: [[/media/itbounce-394.mp3][itbounce-394.mp3]]

** Episode 435
{{< audio src="/media/itbounce-435.mp3" >}}
Download: [[/media/itbounce-435.mp3][itbounce-435.mp3]]

** Episode 456
{{< audio src="/media/itbounce-456.mp3" >}}
Download: [[/media/itbounce-456.mp3][itbounce-456.mp3]]

** Episode 481
{{< audio src="/media/itbounce-481.mp3" >}}
Download: [[/media/itbounce-481.mp3][itbounce-481.mp3]]

** Episode 506
{{< audio src="/media/itbounce-506.mp3" >}}
Download: [[/media/itbounce-506.mp3][itbounce-506.mp3]]

** Episode 519
{{< audio src="/media/itbounce-519.mp3" >}}
Download: [[/media/itbounce-519.mp3][itbounce-519.mp3]]

** Episode 534
{{< audio src="/media/itbounce-534.mp3" >}}
Download: [[/media/itbounce-534.mp3][itbounce-534.mp3]]

** Episode 565
{{< audio src="/media/itbounce-565.mp3" >}}
Download: [[/media/itbounce-565.mp3][itbounce-565.mp3]]

** Episode 579
{{< audio src="/media/itbounce-579.mp3" >}}
Download: [[/media/itbounce-579.mp3][itbounce-579.mp3]]

** Episode 596
{{< audio src="/media/itbounce-596.mp3" >}}
Download: [[/media/itbounce-596.mp3][itbounce-596.mp3]]

** Episode 621
{{< audio src="/media/itbounce-621.mp3" >}}
Download: [[/media/itbounce-621.mp3][itbounce-621.mp3]]

** Episode 654
{{< audio src="/media/itbounce-654.mp3" >}}
Download: [[/media/itbounce-654.mp3][itbounce-654.mp3]]

** Episode 693
{{< audio src="/media/itbounce-693.mp3" >}}
Download: [[/media/itbounce-693.mp3][itbounce-693.mp3]]

** Episode 711
{{< audio src="/media/itbounce-711.mp3" >}}
Download: [[/media/itbounce-711.mp3][itbounce-711.mp3]]

** Episode 712
{{< audio src="/media/itbounce-712.mp3" >}}
Download: [[/media/itbounce-712.mp3][itbounce-712.mp3]]

** Episode 760
{{< audio src="/media/itbounce-760.mp3" >}}
Download: [[/media/itbounce-760.mp3][itbounce-760.mp3]]

** Episode 784
{{< audio src="/media/itbounce-784.mp3" >}}
Download: [[/media/itbounce-784.mp3][itbounce-784.mp3]]

** Episode 814
{{< audio src="/media/itbounce-814.mp3" >}}
Download: [[/media/itbounce-814.mp3][itbounce-814.mp3]]

** Episode 834
{{< audio src="/media/itbounce-834.mp3" >}}
Download: [[/media/itbounce-834.mp3][itbounce-834.mp3]]

** Episode 887
{{< audio src="/media/itbounce-887.mp3" >}}
Download: [[/media/itbounce-887.mp3][itbounce-887.mp3]]

** Episode 916
{{< audio src="/media/itbounce-916.mp3" >}}
Download: [[/media/itbounce-916.mp3][itbounce-916.mp3]]

** Episode 976
{{< audio src="/media/itbounce-976.mp3" >}}
Download: [[/media/itbounce-976.mp3][itbounce-976.mp3]]

** Episode 980
{{< audio src="/media/itbounce-980.mp3" >}}
Download: [[/media/itbounce-980.mp3][itbounce-980.mp3]]

** Episode 1042
{{< audio src="/media/itbounce-1042.mp3" >}}
Download: [[/media/itbounce-1042.mp3][itbounce-1042.mp3]]

** Episode 1066
{{< audio src="/media/itbounce-1066.mp3" >}}
Download: [[/media/itbounce-1066.mp3][itbounce-1066.mp3]]

** Episode 1097
{{< audio src="/media/itbounce-1097.mp3" >}}
Download: [[/media/itbounce-1097.mp3][itbounce-1097.mp3]]

** Episode 1122
{{< audio src="/media/itbounce-1122.mp3" >}}
Download: [[/media/itbounce-1122.mp3][itbounce-1122.mp3]]

** Episode 1156
{{< audio src="/media/itbounce-1156.mp3" >}}
Download: [[/media/itbounce-1156.mp3][itbounce-1156.mp3]]

** Episode 1195
{{< audio src="/media/itbounce-1195.mp3" >}}
Download: [[/media/itbounce-1195.mp3][itbounce-1195.mp3]]

** Episode 1226
{{< audio src="/media/itbounce-1226.mp3" >}}
Download: [[/media/itbounce-1226.mp3][itbounce-1226.mp3]]

** Episode 1249
{{< audio src="/media/itbounce-1249.mp3" >}}
Download: [[/media/itbounce-1249.mp3][itbounce-1249.mp3]]

** Episode rockofonia009
{{< audio src="/media/rockofonia009.mp3" >}}
Download: [[/media/rockofonia009.mp3][rockofonia009.mp3]]

** Episode rockofonia073
{{< audio src="/media/rockofonia073.mp3" >}}
Download: [[/media/rockofonia073.mp3][rockofonia073.mp3]]

** Episode rockofonia074
{{< audio src="/media/rockofonia074.mp3" >}}
Download: [[/media/rockofonia074.mp3][rockofonia074.mp3]]

** Episode rockofonia075
{{< audio src="/media/rockofonia075.mp3" >}}
Download: [[/media/rockofonia075.mp3][rockofonia075.mp3]]

** Episode rockofonia076
{{< audio src="/media/rockofonia076.mp3" >}}
Download: [[/media/rockofonia076.mp3][rockofonia076.mp3]]

** Episode rockofonia077
{{< audio src="/media/rockofonia077.mp3" >}}
Download: [[/media/rockofonia077.mp3][rockofonia077.mp3]]

** Episode rockofonia078
{{< audio src="/media/rockofonia078.mp3" >}}
Download: [[/media/rockofonia078.mp3][rockofonia078.mp3]]

** Episode rockofonia079
{{< audio src="/media/rockofonia079.mp3" >}}
Download: [[/media/rockofonia079.mp3][rockofonia079.mp3]]

** Episode rockofonia080
{{< audio src="/media/rockofonia080.mp3" >}}
Download: [[/media/rockofonia080.mp3][rockofonia080.mp3]]

** Episode rockofonia081
{{< audio src="/media/rockofonia081.mp3" >}}
Download: [[/media/rockofonia081.mp3][rockofonia081.mp3]]

** Episode rockofonia082
{{< audio src="/media/rockofonia082.mp3" >}}
Download: [[/media/rockofonia082.mp3][rockofonia082.mp3]]

** Episode rockofonia083
{{< audio src="/media/rockofonia083.mp3" >}}
Download: [[/media/rockofonia083.mp3][rockofonia083.mp3]]

** Episode rockofonia084
{{< audio src="/media/rockofonia084.mp3" >}}
Download: [[/media/rockofonia084.mp3][rockofonia084.mp3]]

** Episode rockofonia085
{{< audio src="/media/rockofonia085.mp3" >}}
Download: [[/media/rockofonia085.mp3][rockofonia085.mp3]]

** Episode rockofonia086
{{< audio src="/media/rockofonia086.mp3" >}}
Download: [[/media/rockofonia086.mp3][rockofonia086.mp3]]

** Episode rockofonia087
{{< audio src="/media/rockofonia087.mp3" >}}
Download: [[/media/rockofonia087.mp3][rockofonia087.mp3]]

** Episode rockofonia088
{{< audio src="/media/rockofonia088.mp3" >}}
Download: [[/media/rockofonia088.mp3][rockofonia088.mp3]]

** Episode rockofonia089
{{< audio src="/media/rockofonia089.mp3" >}}
Download: [[/media/rockofonia089.mp3][rockofonia089.mp3]]

** Episode rockofonia090
{{< audio src="/media/rockofonia090.mp3" >}}
Download: [[/media/rockofonia090.mp3][rockofonia090.mp3]]

** Episode rockofonia091
{{< audio src="/media/rockofonia091.mp3" >}}
Download: [[/media/rockofonia091.mp3][rockofonia091.mp3]]

** Episode rockofonia092
{{< audio src="/media/rockofonia092.mp3" >}}
Download: [[/media/rockofonia092.mp3][rockofonia092.mp3]]

** Episode rockofonia093
{{< audio src="/media/rockofonia093.mp3" >}}
Download: [[/media/rockofonia093.mp3][rockofonia093.mp3]]

** Episode rockofonia094
{{< audio src="/media/rockofonia094.mp3" >}}
Download: [[/media/rockofonia094.mp3][rockofonia094.mp3]]

** Episode rockofonia095
{{< audio src="/media/rockofonia095.mp3" >}}
Download: [[/media/rockofonia095.mp3][rockofonia095.mp3]]

** Episode rockofonia096
{{< audio src="/media/rockofonia096.mp3" >}}
Download: [[/media/rockofonia096.mp3][rockofonia096.mp3]]

** Episode rockofonia097
{{< audio src="/media/rockofonia097.mp3" >}}
Download: [[/media/rockofonia097.mp3][rockofonia097.mp3]]

** Episode rockofonia098
{{< audio src="/media/rockofonia098.mp3" >}}
Download: [[/media/rockofonia098.mp3][rockofonia098.mp3]]

** Episode rockofonia099
{{< audio src="/media/rockofonia099.mp3" >}}
Download: [[/media/rockofonia099.mp3][rockofonia099.mp3]]

** Episode rockofonia100
{{< audio src="/media/rockofonia100.mp3" >}}
Download: [[/media/rockofonia100.mp3][rockofonia100.mp3]]

** Episode rockofonia101
{{< audio src="/media/rockofonia101.mp3" >}}
Download: [[/media/rockofonia101.mp3][rockofonia101.mp3]]

** Episode rockofonia102
{{< audio src="/media/rockofonia102.mp3" >}}
Download: [[/media/rockofonia102.mp3][rockofonia102.mp3]]

** Episode rockofonia103
{{< audio src="/media/rockofonia103.mp3" >}}
Download: [[/media/rockofonia103.mp3][rockofonia103.mp3]]

** Episode rockofonia104
{{< audio src="/media/rockofonia104.mp3" >}}
Download: [[/media/rockofonia104.mp3][rockofonia104.mp3]]

** Episode rockofonia105
{{< audio src="/media/rockofonia105.mp3" >}}
Download: [[/media/rockofonia105.mp3][rockofonia105.mp3]]

** Episode rockofonia106
{{< audio src="/media/rockofonia106.mp3" >}}
Download: [[/media/rockofonia106.mp3][rockofonia106.mp3]]

** Episode rockofonia107
{{< audio src="/media/rockofonia107.mp3" >}}
Download: [[/media/rockofonia107.mp3][rockofonia107.mp3]]

** Episode rockofonia108
{{< audio src="/media/rockofonia108.mp3" >}}
Download: [[/media/rockofonia108.mp3][rockofonia108.mp3]]

** Episode rockofonia109
{{< audio src="/media/rockofonia109.mp3" >}}
Download: [[/media/rockofonia109.mp3][rockofonia109.mp3]]

** Episode rockofonia110
{{< audio src="/media/rockofonia110.mp3" >}}
Download: [[/media/rockofonia110.mp3][rockofonia110.mp3]]

** Episode rockofonia111
{{< audio src="/media/rockofonia111.mp3" >}}
Download: [[/media/rockofonia111.mp3][rockofonia111.mp3]]

** Episode rockofonia112
{{< audio src="/media/rockofonia112.mp3" >}}
Download: [[/media/rockofonia112.mp3][rockofonia112.mp3]]

** Episode rockofonia113
{{< audio src="/media/rockofonia113.mp3" >}}
Download: [[/media/rockofonia113.mp3][rockofonia113.mp3]]

** Episode rockofonia114
{{< audio src="/media/rockofonia114.mp3" >}}
Download: [[/media/rockofonia114.mp3][rockofonia114.mp3]]

** Episode rockofonia115
{{< audio src="/media/rockofonia115.mp3" >}}
Download: [[/media/rockofonia115.mp3][rockofonia115.mp3]]

** Episode rockofonia116
{{< audio src="/media/rockofonia116.mp3" >}}
Download: [[/media/rockofonia116.mp3][rockofonia116.mp3]]

** Episode rockofonia117
{{< audio src="/media/rockofonia117.mp3" >}}
Download: [[/media/rockofonia117.mp3][rockofonia117.mp3]]

** Episode rockofonia118
{{< audio src="/media/rockofonia118.mp3" >}}
Download: [[/media/rockofonia118.mp3][rockofonia118.mp3]]

** Episode rockofonia119
{{< audio src="/media/rockofonia119.mp3" >}}
Download: [[/media/rockofonia119.mp3][rockofonia119.mp3]]

** Episode rockofonia120
{{< audio src="/media/rockofonia120.mp3" >}}
Download: [[/media/rockofonia120.mp3][rockofonia120.mp3]]

** Episode rockofonia121
{{< audio src="/media/rockofonia121.mp3" >}}
Download: [[/media/rockofonia121.mp3][rockofonia121.mp3]]

** Episode rockofonia122
{{< audio src="/media/rockofonia122.mp3" >}}
Download: [[/media/rockofonia122.mp3][rockofonia122.mp3]]

** Episode rockofonia123
{{< audio src="/media/rockofonia123.mp3" >}}
Download: [[/media/rockofonia123.mp3][rockofonia123.mp3]]

** Episode Rockofonia124
{{< audio src="/media/Rockofonia124.mp3" >}}
Download: [[/media/Rockofonia124.mp3][Rockofonia124.mp3]]

** Episode rockofonia125
{{< audio src="/media/rockofonia125.mp3" >}}
Download: [[/media/rockofonia125.mp3][rockofonia125.mp3]]

** Episode rockofonia126
{{< audio src="/media/rockofonia126.mp3" >}}
Download: [[/media/rockofonia126.mp3][rockofonia126.mp3]]

** Episode rockofonia127
{{< audio src="/media/rockofonia127.mp3" >}}
Download: [[/media/rockofonia127.mp3][rockofonia127.mp3]]

** Episode Rockofonia128
{{< audio src="/media/Rockofonia128.mp3" >}}
Download: [[/media/Rockofonia128.mp3][Rockofonia128.mp3]]

** Episode rockofonia129
{{< audio src="/media/rockofonia129.mp3" >}}
Download: [[/media/rockofonia129.mp3][rockofonia129.mp3]]

** Episode rockofonia130
{{< audio src="/media/rockofonia130.mp3" >}}
Download: [[/media/rockofonia130.mp3][rockofonia130.mp3]]

** Episode rockofonia131
{{< audio src="/media/rockofonia131.mp3" >}}
Download: [[/media/rockofonia131.mp3][rockofonia131.mp3]]

** Episode rockofonia132
{{< audio src="/media/rockofonia132.mp3" >}}
Download: [[/media/rockofonia132.mp3][rockofonia132.mp3]]

** Episode rockofonia133
{{< audio src="/media/rockofonia133.mp3" >}}
Download: [[/media/rockofonia133.mp3][rockofonia133.mp3]]

** Episode rockofonia134
{{< audio src="/media/rockofonia134.mp3" >}}
Download: [[/media/rockofonia134.mp3][rockofonia134.mp3]]

** Episode rockofonia135
{{< audio src="/media/rockofonia135.mp3" >}}
Download: [[/media/rockofonia135.mp3][rockofonia135.mp3]]

** Episode rockofonia136
{{< audio src="/media/rockofonia136.mp3" >}}
Download: [[/media/rockofonia136.mp3][rockofonia136.mp3]]

** Episode rockofonia137
{{< audio src="/media/rockofonia137.mp3" >}}
Download: [[/media/rockofonia137.mp3][rockofonia137.mp3]]

** Episode rockofonia138
{{< audio src="/media/rockofonia138.mp3" >}}
Download: [[/media/rockofonia138.mp3][rockofonia138.mp3]]

** Episode rockofonia139
{{< audio src="/media/rockofonia139.mp3" >}}
Download: [[/media/rockofonia139.mp3][rockofonia139.mp3]]

** Episode rockofonia140
{{< audio src="/media/rockofonia140.mp3" >}}
Download: [[/media/rockofonia140.mp3][rockofonia140.mp3]]

** Episode rockofonia141
{{< audio src="/media/rockofonia141.mp3" >}}
Download: [[/media/rockofonia141.mp3][rockofonia141.mp3]]

** Episode rockofonia142
{{< audio src="/media/rockofonia142.mp3" >}}
Download: [[/media/rockofonia142.mp3][rockofonia142.mp3]]

** Episode rockofonia143
{{< audio src="/media/rockofonia143.mp3" >}}
Download: [[/media/rockofonia143.mp3][rockofonia143.mp3]]

** Episode rockofonia144
{{< audio src="/media/rockofonia144.mp3" >}}
Download: [[/media/rockofonia144.mp3][rockofonia144.mp3]]

** Episode rockofonia145
{{< audio src="/media/rockofonia145.mp3" >}}
Download: [[/media/rockofonia145.mp3][rockofonia145.mp3]]

** Episode rockofonia146
{{< audio src="/media/rockofonia146.mp3" >}}
Download: [[/media/rockofonia146.mp3][rockofonia146.mp3]]

** Episode rockofonia147
{{< audio src="/media/rockofonia147.mp3" >}}
Download: [[/media/rockofonia147.mp3][rockofonia147.mp3]]

** Episode rockofonia148
{{< audio src="/media/rockofonia148.mp3" >}}
Download: [[/media/rockofonia148.mp3][rockofonia148.mp3]]

** Episode rockofonia149
{{< audio src="/media/rockofonia149.mp3" >}}
Download: [[/media/rockofonia149.mp3][rockofonia149.mp3]]

** Episode rockofonia150
{{< audio src="/media/rockofonia150.mp3" >}}
Download: [[/media/rockofonia150.mp3][rockofonia150.mp3]]

** Episode rockofonia151
{{< audio src="/media/rockofonia151.mp3" >}}
Download: [[/media/rockofonia151.mp3][rockofonia151.mp3]]

** Episode rockofonia152
{{< audio src="/media/rockofonia152.mp3" >}}
Download: [[/media/rockofonia152.mp3][rockofonia152.mp3]]

** Episode rockofonia153
{{< audio src="/media/rockofonia153.mp3" >}}
Download: [[/media/rockofonia153.mp3][rockofonia153.mp3]]

** Episode rockofonia154
{{< audio src="/media/rockofonia154.mp3" >}}
Download: [[/media/rockofonia154.mp3][rockofonia154.mp3]]

** Episode rockofonia155
{{< audio src="/media/rockofonia155.mp3" >}}
Download: [[/media/rockofonia155.mp3][rockofonia155.mp3]]

** Episode rockofonia156
{{< audio src="/media/rockofonia156.mp3" >}}
Download: [[/media/rockofonia156.mp3][rockofonia156.mp3]]

** Episode rockofonia157
{{< audio src="/media/rockofonia157.mp3" >}}
Download: [[/media/rockofonia157.mp3][rockofonia157.mp3]]

** Episode rockofonia158
{{< audio src="/media/rockofonia158.mp3" >}}
Download: [[/media/rockofonia158.mp3][rockofonia158.mp3]]

** Episode rockofonia159
{{< audio src="/media/rockofonia159.mp3" >}}
Download: [[/media/rockofonia159.mp3][rockofonia159.mp3]]

** Episode rockofonia160
{{< audio src="/media/rockofonia160.mp3" >}}
Download: [[/media/rockofonia160.mp3][rockofonia160.mp3]]

** Episode rockofonia161
{{< audio src="/media/rockofonia161.mp3" >}}
Download: [[/media/rockofonia161.mp3][rockofonia161.mp3]]

** Episode rockofonia162
{{< audio src="/media/rockofonia162.mp3" >}}
Download: [[/media/rockofonia162.mp3][rockofonia162.mp3]]

** Episode rockofonia163
{{< audio src="/media/rockofonia163.mp3" >}}
Download: [[/media/rockofonia163.mp3][rockofonia163.mp3]]

** Episode rockofonia164
{{< audio src="/media/rockofonia164.mp3" >}}
Download: [[/media/rockofonia164.mp3][rockofonia164.mp3]]

** Episode rockofonia165
{{< audio src="/media/rockofonia165.mp3" >}}
Download: [[/media/rockofonia165.mp3][rockofonia165.mp3]]

** Episode rockofonia166
{{< audio src="/media/rockofonia166.mp3" >}}
Download: [[/media/rockofonia166.mp3][rockofonia166.mp3]]

** Episode rockofonia167
{{< audio src="/media/rockofonia167.mp3" >}}
Download: [[/media/rockofonia167.mp3][rockofonia167.mp3]]

** Episode rockofonia168
{{< audio src="/media/rockofonia168.mp3" >}}
Download: [[/media/rockofonia168.mp3][rockofonia168.mp3]]

** Episode rockofonia169
{{< audio src="/media/rockofonia169.mp3" >}}
Download: [[/media/rockofonia169.mp3][rockofonia169.mp3]]

** Episode rockofonia170
{{< audio src="/media/rockofonia170.mp3" >}}
Download: [[/media/rockofonia170.mp3][rockofonia170.mp3]]

** Episode rockofonia171
{{< audio src="/media/rockofonia171.mp3" >}}
Download: [[/media/rockofonia171.mp3][rockofonia171.mp3]]

** Episode rockofonia172
{{< audio src="/media/rockofonia172.mp3" >}}
Download: [[/media/rockofonia172.mp3][rockofonia172.mp3]]

** Episode rockofonia173
{{< audio src="/media/rockofonia173.mp3" >}}
Download: [[/media/rockofonia173.mp3][rockofonia173.mp3]]

** Episode rockofonia174
{{< audio src="/media/rockofonia174.mp3" >}}
Download: [[/media/rockofonia174.mp3][rockofonia174.mp3]]

** Episode rockofonia175
{{< audio src="/media/rockofonia175.mp3" >}}
Download: [[/media/rockofonia175.mp3][rockofonia175.mp3]]

** Episode rockofonia176
{{< audio src="/media/rockofonia176.mp3" >}}
Download: [[/media/rockofonia176.mp3][rockofonia176.mp3]]

** Episode rockofonia177
{{< audio src="/media/rockofonia177.mp3" >}}
Download: [[/media/rockofonia177.mp3][rockofonia177.mp3]]

** Episode rockofonia178
{{< audio src="/media/rockofonia178.mp3" >}}
Download: [[/media/rockofonia178.mp3][rockofonia178.mp3]]

** Episode rockofonia180
{{< audio src="/media/rockofonia180.mp3" >}}
Download: [[/media/rockofonia180.mp3][rockofonia180.mp3]]

** Episode rockofonia181
{{< audio src="/media/rockofonia181.mp3" >}}
Download: [[/media/rockofonia181.mp3][rockofonia181.mp3]]

** Episode rockofonia182
{{< audio src="/media/rockofonia182.mp3" >}}
Download: [[/media/rockofonia182.mp3][rockofonia182.mp3]]

** Episode rockofonia183
{{< audio src="/media/rockofonia183.mp3" >}}
Download: [[/media/rockofonia183.mp3][rockofonia183.mp3]]

** Episode rockofonia184
{{< audio src="/media/rockofonia184.mp3" >}}
Download: [[/media/rockofonia184.mp3][rockofonia184.mp3]]

** Episode rockofonia185
{{< audio src="/media/rockofonia185.mp3" >}}
Download: [[/media/rockofonia185.mp3][rockofonia185.mp3]]

** Episode rockofonia186
{{< audio src="/media/rockofonia186.mp3" >}}
Download: [[/media/rockofonia186.mp3][rockofonia186.mp3]]

** Season 1 final episode
{{< audio src="/media/rockofonia-final.mp3" >}}
Download: [[/media/rockofonia-final.mp3][rockofonia-final.mp3]]

** Episode rockofonia200
{{< audio src="/media/rockofonia200.mp3" >}}
Download: [[/media/rockofonia200.mp3][rockofonia200.mp3]]

** Episode rockofonia201
{{< audio src="/media/rockofonia201.mp3" >}}
Download: [[/media/rockofonia201.mp3][rockofonia201.mp3]]

** Episode rockofonia202
{{< audio src="/media/rockofonia202.mp3" >}}
Download: [[/media/rockofonia202.mp3][rockofonia202.mp3]]

** Episode rockofonia203
{{< audio src="/media/rockofonia203.mp3" >}}
Download: [[/media/rockofonia203.mp3][rockofonia203.mp3]]

** Episode rockofonia204
{{< audio src="/media/rockofonia204.mp3" >}}
Download: [[/media/rockofonia204.mp3][rockofonia204.mp3]]

** Episode rockofonia205
{{< audio src="/media/rockofonia205.mp3" >}}
Download: [[/media/rockofonia205.mp3][rockofonia205.mp3]]

** Episode rockofonia206
{{< audio src="/media/rockofonia206.mp3" >}}
Download: [[/media/rockofonia206.mp3][rockofonia206.mp3]]

** Episode rockofonia207
{{< audio src="/media/rockofonia207.mp3" >}}
Download: [[/media/rockofonia207.mp3][rockofonia207.mp3]]

** Episode rockofonia208
{{< audio src="/media/rockofonia208.mp3" >}}
Download: [[/media/rockofonia208.mp3][rockofonia208.mp3]]

** Episode rockofonia209
{{< audio src="/media/rockofonia209.mp3" >}}
Download: [[/media/rockofonia209.mp3][rockofonia209.mp3]]

** Episode rockofonia210
{{< audio src="/media/rockofonia210.mp3" >}}
Download: [[/media/rockofonia210.mp3][rockofonia210.mp3]]

** Episode rockofonia211
{{< audio src="/media/rockofonia211.mp3" >}}
Download: [[/media/rockofonia211.mp3][rockofonia211.mp3]]

** Episode rockofonia212
{{< audio src="/media/rockofonia212.mp3" >}}
Download: [[/media/rockofonia212.mp3][rockofonia212.mp3]]

** Episode rockofonia213
{{< audio src="/media/rockofonia213.mp3" >}}
Download: [[/media/rockofonia213.mp3][rockofonia213.mp3]]

** Episode rockofonia214
{{< audio src="/media/rockofonia214.mp3" >}}
Download: [[/media/rockofonia214.mp3][rockofonia214.mp3]]

** Episode rockofonia215
{{< audio src="/media/rockofonia215.mp3" >}}
Download: [[/media/rockofonia215.mp3][rockofonia215.mp3]]

** Episode rockofonia216
{{< audio src="/media/rockofonia216.mp3" >}}
Download: [[/media/rockofonia216.mp3][rockofonia216.mp3]]

** Episode rockofonia217
{{< audio src="/media/rockofonia217.mp3" >}}
Download: [[/media/rockofonia217.mp3][rockofonia217.mp3]]

** Episode rockofonia218
{{< audio src="/media/rockofonia218.mp3" >}}
Download: [[/media/rockofonia218.mp3][rockofonia218.mp3]]

** Episode rockofonia219
{{< audio src="/media/rockofonia219.mp3" >}}
Download: [[/media/rockofonia219.mp3][rockofonia219.mp3]]

** Episode rockofonia220
{{< audio src="/media/rockofonia220.mp3" >}}
Download: [[/media/rockofonia220.mp3][rockofonia220.mp3]]

** Episode rockofonia221
{{< audio src="/media/rockofonia221.mp3" >}}
Download: [[/media/rockofonia221.mp3][rockofonia221.mp3]]

** Episode rockofonia222
{{< audio src="/media/rockofonia222.mp3" >}}
Download: [[/media/rockofonia222.mp3][rockofonia222.mp3]]

** Episode rockofonia223
{{< audio src="/media/rockofonia223.mp3" >}}
Download: [[/media/rockofonia223.mp3][rockofonia223.mp3]]

** Episode rockofonia224
{{< audio src="/media/rockofonia224.mp3" >}}
Download: [[/media/rockofonia224.mp3][rockofonia224.mp3]]
